services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    networks:
      - app-network


  laravel:
    build:
      context: ./Hefesto-Backend
      dockerfile: Dockerfile
    container_name: laravel-app
   # volumes:
   #   - ./backend:/var/www/html
    ports:
      - "8000:80"
    networks:
      - app-network
    environment:
      - APP_DEBUG=true
      - APP_KEY=base64:somekey==base64:klPBaYGK/28Rm8B2kc4OuTA2mcMNJl03mkpr+O1R1aI=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_HOST=172.20.227.241
      - DB_DATABASE=grupo6_2425
      - DB_PASSWORD=F(t[Hj-rC5XRKtGj
    depends_on:
      - db


  frontend:
    build:
      context: ./Hefesto-Frontend
      dockerfile: Dockerfile
    container_name: vue-app
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - laravel
    environment:
      - VITE_API_AUTH_URL=${VITE_API_AUTH_URL}

networks:
  app-network:
    driver: bridge
